version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LOCAL_GRPC_PORT}:${CONTAINER_GRPC_PORT}
      - ${LOCAL_REST_PORT}:${CONTAINER_REST_PORT}
    container_name: web_backend
    env_file: docker-compose.env